---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: jmeter
data:
  load_test: |
    # !/bin/bash
    #
    # Script created to invoke jmeter test script with the worker POD IP addresses
    # Script should be run like: ./load_test <path-to-local-jmx>
    /jmeter/apache-jmeter-5.4.3/bin/jmeter -n -t $1 -D server.rmi.ssl.disable=true -J httpsampler.ignore_failed_embedded_resources=true -R jmeter-workers-svc.default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmeter-master
        image: jrudio/jmeter-master:v1
        imagePullPolicy: Always
        env:
        resources:
          requests:
            memory: "512Mi"
            cpu: "150m"
          limits:
            memory: "2096Mi"
            cpu: "940m"
            # memory: "4096Mi"
            # cpu: "3000m"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: load-test
          mountPath: /load_test
          subPath: "load_test"
        ports:
        - containerPort: 60000
      volumes:
      - name: load-test
        configMap:
          name: jmeter-load-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-workers
  labels:
    jmeter_mode: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      jmeter_mode: worker
  template:
    metadata:
      labels:
        jmeter_mode: worker
    spec:
      containers:
      - name: jmeter-worker
        image: jrudio/jmeter-worker:v1
        env:
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "1500m"
        ports:
        - containerPort: 1099
        - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-workers-svc
  labels:
    jmeter_mode: worker
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: worker